name: Check Commits

on:
  workflow_call:

jobs:
  check-commit-message:
    runs-on: arc
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check commit message format
        run: |
          COMMIT_PATTERN="^(feat|fix|docs|style|refactor|test|chore|build|ci|perf)(\([a-z0-9-]+\))?(!)?: .+$"

          BASE_REF=${{ github.event.pull_request.base.ref }}
          COMMITS=$(git log --no-merges --format="%H" origin/$BASE_REF..HEAD)
          
          echo "Validating commits..."
          
          for COMMIT_HASH in $COMMITS; do
            COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s" ${COMMIT_HASH})
            echo "Validating commit hash: ${COMMIT_HASH}, with message: ${COMMIT_MESSAGE}..."
            if [[ ! $COMMIT_MESSAGE =~ $COMMIT_PATTERN ]]; then
              echo "ERROR: Commit message is not compliant!"
              echo "Commit messages must follow: <type>[(scope)][!]: <message>"
              echo "Types allowed: feat|fix|docs|style|refactor|test|chore|build|ci|perf"
              echo ""
              echo "Your commit message: $COMMIT_MESSAGE"
              exit 1
            fi
          done

          echo "All commit messages are compliant! ✅"
